before_script:
  - apt-get update -qq && apt-get install -y python python3 python3-pip python-pip fabric python-virtualenv
  - fab test.mkenv
  - mkdir -p www/docs

test:
  script:
    - fab test.all

docs:
  script:
    - fab docs.build