before_script:
  - apt-get update -qq && apt-get install -y python python3 python3-pip python-pip fabric python-virtualenv nodejs npm
  - fab test.mkenv
  - mkdir -p www/docs
  - ln -s /usr/bin/nodejs /usr/bin/node
  - npm install -g phantomjs

test:
  script:
    - fab test.server
    - bash <(curl -s https://codecov.io/bash)

docs:
  script:
    - fab docs.build
  stage: deploy
  script:
    - fab docs.build
  artifacts:
    paths:
    - www/docs/
  only:
    - master
