language: python

python:
  - "3.4"

cache: pip

# command to install dependencies
install:
  - pip install -r requirements.txt
  - npm install phantomjs

# Tests
script: ./management/test/run_tests.sh
